language: node_js
node_js:
  - '8'
  - v12
  - v10
  - v8
  - v6
cache:
  directories:
  - node_modules
after_script: cat ./coverage/lcov.info | coveralls
deploy:
        provider: npm
        api_key: $NPM_API_KEY
        on: master